FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /src
COPY . .
RUN dotnet restore "./TaskManager.API/TaskManager.API.csproj"
RUN dotnet ef database update --project TaskManager.API/TaskManager.API.csproj
